import * as assert from "node:assert/strict";
import { App, openTestModals } from "obsidian";
import { mountAccountMembership, appendAccountComingSoon } from "../settings/account-membership";
import { createUnavailableAccountAdapter, type AccountMembershipViewModel } from "../settings/account-membership-model";
import { normalizeSettingsData, DEFAULT_SETTINGS } from "../settings/settings";
import { prepareDocument, fixture, mountDefinitions } from "./settings-search-dom";
import { runAccountMembershipPricingTests } from "./account-membership-pricing";
import { runAccountMembershipSubscriptionTests } from "./account-membership-subscription";

export async function runAccountMembershipTests(win: Window & typeof globalThis) {
  runAccountMembershipPricingTests();
  const scheduler = prepareDocument(win);
  const adapter = createUnavailableAccountAdapter();
  const vm = adapter.read();
  assert.equal(vm.identity, null);
  assert.equal(vm.serviceAvailable, false);
  assert.equal(vm.statistics.totalTokens, null);
  assert.equal(vm.membership.devices, null);
  assert.equal(vm.provider, "unknown");
  assert.deepEqual(adapter.actions, {});
  assert.equal(normalizeSettingsData({ settingsTab: "account" }).settings.settingsTab, "account");
  assert.equal(normalizeSettingsData({ settingsTab: "not-a-tab" }).settings.settingsTab, DEFAULT_SETTINGS.settingsTab);
  const snapshot = JSON.stringify(vm);
  const parent = win.document.createElement("div"); win.document.body.appendChild(parent);
  let calls = 0;
  let currentVm = vm;
  const mount = () => mountAccountMembership(parent, { app: new App(), viewModel: currentVm, language: "zh-CN", actions: { signIn: async () => { calls++; }, saveProfile: async () => { calls++; }, setPassword: async () => { calls++; } }, openProviders: () => { calls++; } });
  const findButton = (root: HTMLElement, text: string) => [...root.querySelectorAll<HTMLButtonElement>("button")].find(button => button.textContent === text)!;
  let page = mount(); await scheduler.flush();
  assert.equal(parent.querySelectorAll(".heat-cell").length, 365);
  assert.equal(parent.querySelectorAll('.heat-cell[tabindex="0"]').length, 1);
  assert.equal(parent.querySelectorAll(".metrics strong")[0].textContent, "—");
  assert.equal(parent.querySelectorAll(".plan").length, 4);
  assert.equal(findButton(parent, "新建计划").disabled, true);
  assert.equal(findButton(parent, "生成讲解").disabled, true);
  assert.equal(parent.querySelectorAll(".plugin-feature-card").length, 2);
  assert.ok(parent.querySelector(".coming-soon.span-full"));
  assert.ok(!parent.querySelector("iframe"));
  assert.equal(findButton(parent, "编辑资料"), undefined, "anonymous cannot edit a fake profile");
  assert.equal(parent.querySelector(".profile-section .avatar"), null);
  assert.equal(parent.querySelector(".membership-footer button"), null, "anonymous has no personal device actions");
  assert.equal(parent.querySelector(".activation-form"), null, "redemption only appears after sign-in");
  findButton(parent, "登录 / 注册").click();
  let modal = openTestModals.at(-1)!; assert.ok(modal);
  const form = modal.contentEl.querySelector("form")!;
  const email = form.querySelector<HTMLInputElement>('input[type="email"]')!; email.value = "synthetic@example.invalid";
  assert.ok(form.querySelector<HTMLButtonElement>('button[type="submit"]')!.disabled);
  form.dispatchEvent(new win.Event("submit", { bubbles: true, cancelable: true })); await Promise.resolve(); assert.equal(calls, 0);
  findButton(modal.contentEl, "密码登录").click();
  const secret = modal.contentEl.querySelector<HTMLInputElement>('input[type="password"]')!; secret.value = "synthetic-only-secret";
  findButton(modal.contentEl, "忘记密码").click();
  assert.equal(secret.value, "", "password field is cleared on modal replacement");
  modal = openTestModals.at(-1)!;
  assert.equal(modal.contentEl.querySelectorAll('input[type="password"]').length, 2);
  assert.ok(modal.contentEl.querySelector<HTMLInputElement>('input[inputmode="numeric"]'));
  win.document.dispatchEvent(new win.KeyboardEvent("keydown", { key: "Escape", bubbles: true, cancelable: true }));
  assert.equal(openTestModals.length, 0);
  const capturedLogin = findButton(parent, "登录 / 注册");
  capturedLogin.click(); assert.equal(openTestModals.length, 1);
  page.dispose(); page.dispose(); capturedLogin.click();
  assert.equal(openTestModals.length, 0, "page teardown closes modals and removes detached event handlers");
  assert.equal(parent.children.length, 0);
  page = mount(); await scheduler.flush();
  assert.equal(parent.querySelectorAll(".echoink-account").length, 1, "remount owns a single component"); page.dispose();
  currentVm = { ...vm, identity: { name: "林同学", email: "synthetic@example.invalid", joinedAt: null, avatar: "initial", passwordSet: false } };
  const originalCreate = win.URL.createObjectURL, originalRevoke = win.URL.revokeObjectURL;
  const created: string[] = [], revoked: string[] = [];
  win.URL.createObjectURL = () => { const url = `blob:synthetic-${created.length}`; created.push(url); return url; };
  win.URL.revokeObjectURL = url => { revoked.push(url); };
  const choose = (file: File) => {
    const picker = openTestModals.at(-1)!.contentEl.querySelector<HTMLInputElement>('input[type="file"]')!;
    Object.defineProperty(picker, "files", { configurable: true, value: [file] }); picker.dispatchEvent(new win.Event("change", { bubbles: true }));
  };
  const image = new win.File([new Uint8Array([137,80,78,71])], "avatar.png", { type: "image/png" });
  page = mount();
  findButton(parent, "设备管理").click(); assert.ok(openTestModals.at(-1)!.contentEl.textContent?.includes("设备信息暂不可用")); openTestModals.at(-1)!.close();
  assert.equal(parent.querySelector(".profile-section .muted"), null, "missing joined date is omitted");
  findButton(parent, "编辑资料").click(); modal = openTestModals.at(-1)!;
  const name = modal.contentEl.querySelector<HTMLInputElement>('input[type="text"]')!; name.value = "未保存的昵称"; name.dispatchEvent(new win.Event("input", { bubbles: true }));
  assert.equal(modal.contentEl.querySelector(".avatar-draft-preview")?.textContent, "未");
  choose(new win.File(["bad"], "avatar.gif", { type: "image/gif" })); assert.equal(created.length, 0);
  choose(new win.File([new Uint8Array(5 * 1024 * 1024 + 1)], "large.png", { type: "image/png" })); assert.equal(created.length, 0);
  choose(image); assert.equal(modal.contentEl.querySelector("img")?.getAttribute("src"), created[0]);
  assert.equal(modal.contentEl.querySelector(".form-error")?.textContent, "");
  findButton(modal.contentEl, "设置密码").click(); modal = openTestModals.at(-1)!;
  assert.equal(modal.contentEl.querySelectorAll('input[type="password"]').length, 2, "no current-password requirement");
  assert.equal(revoked.length, 0, "password transition retains image draft");
  findButton(modal.contentEl, "返回").click(); modal = openTestModals.at(-1)!;
  assert.equal(modal.contentEl.querySelector<HTMLInputElement>('input[type="text"]')!.value, "未保存的昵称");
  assert.equal(modal.contentEl.querySelector("img")?.getAttribute("src"), created[0]);
  choose(new win.File(["jpeg"], "next.jpg", { type: "image/jpeg" })); assert.deepEqual(revoked, [created[0]], "replacement releases previous draft");
  findButton(modal.contentEl, "恢复默认").click(); assert.deepEqual(revoked, created); assert.equal(modal.contentEl.querySelector("img"), null);
  choose(image); modal.close(); assert.deepEqual(revoked, created, "cancel releases image");
  findButton(parent, "编辑资料").click(); modal = openTestModals.at(-1)!;
  assert.equal(modal.contentEl.querySelector<HTMLInputElement>('input[type="text"]')!.value, "林同学");
  choose(image); modal.contentEl.querySelector("img")!.dispatchEvent(new win.Event("error"));
  assert.equal(modal.contentEl.querySelector("img"), null, "unreadable image restores default"); assert.deepEqual(revoked, created);
  choose(image); findButton(modal.contentEl, "设置密码").click(); page.dispose(); assert.deepEqual(revoked, created, "unmount from password releases retained image");
  assert.equal(JSON.stringify(vm), snapshot, "form drafts never mutate display model");
  page = mountAccountMembership(parent, { app: new App(), viewModel: { ...currentVm, membership: { ...currentVm.membership, devices: [] } }, language: "zh-CN", openProviders() {} });
  findButton(parent, "设备管理 · 0 / —").click(); assert.ok(openTestModals.at(-1)!.contentEl.textContent?.includes("暂无已激活设备")); page.dispose();
  let saved: { name: string; avatar?: File | null } | undefined;
  page = mountAccountMembership(parent, { app: new App(), viewModel: { ...currentVm, serviceAvailable: true }, language: "zh-CN", actions: { saveProfile: async input => { saved = input; } }, openProviders() {} });
  findButton(parent, "编辑资料").click(); modal = openTestModals.at(-1)!; choose(image);
  findButton(modal.contentEl, "保存资料").click(); await Promise.resolve(); await Promise.resolve();
  assert.equal(saved?.avatar, image, "adapter receives original File, not blob URL"); assert.deepEqual(revoked, created);
  page.dispose();
  const customVm: AccountMembershipViewModel = { ...currentVm, serviceAvailable: true, identity: { ...currentVm.identity!, avatar: { url: "blob:external-owned-image" } } };
  page = mountAccountMembership(parent, { app: new App(), viewModel: customVm, language: "zh-CN", actions: { saveProfile: async input => { saved = input; } }, openProviders() {} });
  findButton(parent, "编辑资料").click(); modal = openTestModals.at(-1)!;
  findButton(modal.contentEl, "保存资料").click(); await Promise.resolve(); await Promise.resolve(); assert.equal(saved?.avatar, undefined, "untouched identity image stays unchanged");
  findButton(parent, "编辑资料").click(); modal = openTestModals.at(-1)!;
  findButton(modal.contentEl, "恢复默认").click(); findButton(modal.contentEl, "保存资料").click(); await Promise.resolve(); await Promise.resolve();
  assert.equal(saved?.avatar, null, "reset explicitly requests the nickname initial"); page.dispose();
  assert.ok(!revoked.includes("blob:external-owned-image"), "draft never revokes adapter-owned URLs");
  win.URL.createObjectURL = originalCreate; win.URL.revokeObjectURL = originalRevoke;
  const partial: AccountMembershipViewModel = { ...vm, statistics: { ...vm.statistics, totalTokens: 0, days: [{ date: "2026-10-06", tokens: 0, turns: null, input: null, output: 0 }], rankings: { all: { models: [{ name: "Actual all-range row", count: 8 }], skills: [] } } } };
  page = mountAccountMembership(parent, { app: new App(), viewModel: partial, language: "en", openProviders() {} });
  assert.equal(parent.querySelector(".metrics strong")?.textContent, "0", "reported zero differs from missing data");
  const last = parent.querySelector<HTMLButtonElement>('.heat-cell[data-date="2026-10-06"]')!;
  assert.ok(last.getAttribute("aria-label")?.includes("0 Token"));
  findButton(parent, "Turns").click(); assert.ok(parent.querySelector('.heat-cell[data-date="2026-10-06"]')?.getAttribute("aria-label")?.includes("No statistics"));
  findButton(parent, "All").click(); assert.ok(parent.querySelector(".rank-title")?.textContent?.includes("Actual all-range row"));
  const tooltip = win.document.querySelector<HTMLElement>(".echoink-account-tooltip")!;
  const focusedCell = parent.querySelector<HTMLButtonElement>('.heat-cell[data-date="2026-10-06"]')!;
  focusedCell.focus(); assert.equal(tooltip.hidden, false); assert.ok(tooltip.textContent?.includes("No statistics"));
  findButton(parent, "Token").click(); assert.equal(tooltip.hidden, true, "metric switch clears old tooltip");
  parent.querySelector<HTMLButtonElement>('.heat-cell[data-date="2026-10-06"]')!.focus(); assert.equal(tooltip.hidden, false);
  win.document.dispatchEvent(new win.KeyboardEvent("keydown", { key: "Escape", bubbles: true })); assert.equal(tooltip.hidden, true);
  parent.querySelector<HTMLButtonElement>('.heat-cell[data-date="2026-10-05"]')!.focus(); assert.equal(tooltip.hidden, false);
  parent.dispatchEvent(new win.Event("scroll")); assert.equal(tooltip.hidden, true);
  const cells = [...parent.querySelectorAll<HTMLButtonElement>(".heat-cell")];
  cells.at(-1)!.dispatchEvent(new win.KeyboardEvent("keydown", { key: "Home", bubbles: true, cancelable: true })); assert.equal(win.document.activeElement, cells[0]);
  page.dispose();
  page = mountAccountMembership(parent, { app: new App(), viewModel: { ...partial, provider: "configured", membership: { ...vm.membership, state: "active" } }, language: "en", openProviders() {} });
  assert.equal(findButton(parent, "New plan").disabled, false, "valid membership sample enables PRO display actions");
  page.dispose();
  const resolvedOptions = Intl.DateTimeFormat.prototype.resolvedOptions;
  try {
    for (const [timeZone, language, prices, savings] of [
      ["Asia/Shanghai", "en", ["¥19.9", "¥9", "¥19", "¥49"], ["-59%", "-30%", "-55%"]],
      ["America/New_York", "zh-CN", ["US$9.99", "US$2.99", "US$6.99", "US$19.99"], ["-50%", "-22%", "-44%"]]
    ] as const) {
      Intl.DateTimeFormat.prototype.resolvedOptions = function () { return { ...resolvedOptions.call(this), timeZone }; };
      page = mountAccountMembership(parent, { app: new App(), viewModel: vm, language, openProviders() {} });
      assert.deepEqual([...parent.querySelectorAll(".price-amount")].map(node => node.textContent), prices, "pricing follows device time zone independently of UI language");
      assert.deepEqual([...parent.querySelectorAll(".plan-saving-percent")].map(node => node.textContent), savings);
      assert.equal(parent.querySelectorAll(".plan")[1].querySelector(".plan-saving"), null, "monthly pass has no discount");
      assert.ok(parent.querySelector(".is-early .plan-comparison")?.textContent?.includes(language === "en" ? "annual pass" : "比年卡少付"), "early comparison names its annual-pass baseline");
      page.dispose();
    }
    Intl.DateTimeFormat.prototype.resolvedOptions = function () { throw new Error("Time zone unavailable"); };
    page = mount();
    assert.equal(parent.querySelector(".price-amount")?.textContent, "US$9.99", "time zone failure keeps the page usable with international prices");
    page.dispose();
  } finally { Intl.DateTimeFormat.prototype.resolvedOptions = resolvedOptions; }
  for (const count of [2, 3]) { const card = appendAccountComingSoon(parent, count, true); assert.equal(card.classList.contains("span-full"), count % 2 === 0); card.remove(); }
  assert.equal(win.document.querySelectorAll(".echoink-account-tooltip").length, 0, "tooltip removed on teardown");
  parent.remove();
  const f = fixture(win, "zh-CN"); f.plugin.settings.settingsTab = "account";
  let native = mountDefinitions(f.tab); await scheduler.flush();
  assert.ok(f.tab.containerEl.querySelector(".echoink-account"));
  findButton(f.tab.containerEl, "登录 / 注册").click(); assert.equal(openTestModals.length, 1);
  f.tab.containerEl.querySelector<HTMLButtonElement>('button[data-settings-tab="providers"]')!.click(); await scheduler.flush();
  assert.equal(openTestModals.length, 0, "category change disposes the account modal");
  f.tab.containerEl.querySelector<HTMLButtonElement>('button[data-settings-tab="account"]')!.click(); await scheduler.flush();
  assert.equal(f.saved.at(-1)!.settingsTab, "account");
  assert.ok(!JSON.stringify(f.saved).includes("synthetic-only-secret"));
  findButton(f.tab.containerEl, "登录 / 注册").click(); f.tab.hide(); assert.equal(openTestModals.length, 0, "settings hide disposes the account component"); native.cleanup();
  native = mountDefinitions(f.tab); await scheduler.flush(); assert.ok(f.tab.containerEl.querySelector(".echoink-account"));
  native.cleanup(); f.registrations.forEach(cleanup => cleanup()); f.tab.containerEl.remove();
  await runAccountMembershipSubscriptionTests(win);
  console.log("PASS account membership: unavailable adapter, partial data, all-range filtering, transient forms, keyboard, parity, native navigation/persistence and teardown");
}
